### ISSUE TITLE
Have you looked at Go's TLS1.3? It's *almost* there!

### ISSUE THREAD

**Issue by jvmatl** [raff/tls-psk#2]
Hi Raffael!

First, thank you for doing this - this package has been a lifesaver. I linked to this work in a discussion about adding PSKs to the standard library (see https://github.com/golang/go/issues/6379)

TL;DR - the TLS1.3 support in Go 1.13 *almost* gives us out of the box PSK support in the std lib. I was wondering if you would consider revisiting this problem and seeing what it would take to support external PSKs in the go TLS1.3 stack the way you did for 1.2: I think it would be a much smaller effort, but I don't feel comfortable enough with the TLS standards to make the change myself..

Either way, thanks again for taking the time to make this available.

**Comment by raff** [comment]
Hi,
I didn't look at the TLS1.3 implementation yet (and actually I didn't touch my PSK implementation in a very long time). I'll see if I have some time during the holidays and if it would be easy enough to update my implementation.

**Comment by raff** [comment]
Ok, I have created a new version based on Go 1.13.4

It was a little trickier than I expected, because of the "jumps" to TLS 1.3 implementation.
Note that this version DOES NOT support TLS 1.3 so you need to explicitly set MaxVersion in tls.Config to tls.VersionTLS12.

I see that there is some support for PSK in the TLS 1.3 implementation but it's only for resumed connection (i.e. there is no support for fully external PSK) and it's not clear to me if there are new cipher suites that can be/should be used for TLS 1.3 so for now I am just skipping it all together.

Anyway, give it a try. If you use modules use:

    require github.com/raff/tls-psk v1.0.0

This should pick the correct version of tls-ext (guess what: v1.0.0 :)

If you don't use modules you can check-out the tls13 branch for both tls-ext and tls-pks (I didn't want to move the new code to the master branch and break current usage). 

Let me know how it works.

**Comment by jvmatl** [comment]
Very cool! I will give this a try first thing tomorrow. I still hope we can eventually persuade the Go team to make the (relatively) small changes to enable PSK with TLS1.3, so none of us need to mess with forked crypto code, but until that day, this is a *huge* help. Thank you.

**Comment by jvmatl** [comment]
Hey Raff! I can successfully connect to tls-psk 1.0.0 with a TLS1.2 client via PSK! 

I'm now in science project mode, trying to figure out the least painful way to use it with net/http - @FiloSottile suggested this should be doable using the vendor folder, but I haven't figured out how to get that working yet. (I'm still new to the modules world, and I don't fully undersand the interaction between modules and vendor/ but I'll get there..)

BTW: Just in case anybody else follows the link from the golang issue to here issue and wants to try it, there is a typo in your 'require' line above (you wrote `tls-pks` instead of `tls-psk`)

**Comment by raff** [comment]
I didn't try but shouldn't you be able to do something like this ?

`tlsConfig := &tls.Config{
                        CipherSuites: []uint16{psk.TLS_PSK_WITH_AES_128_CBC_SHA},
                        Certificates: []tls.Certificate{tls.Certificate{}},
                        Extra: psk.PSKConfig{
                                GetKey:      getKey,
                                GetIdentity: nil,
                        },
                }

  var srv http.Server
  ...
  l, err := tls.Listen(network, addr, tlsConfig)
  ...
  srv.Serve(l)`

As long as you don't call any specific TLS method in net/http you should be fine mixing net/http with a separate implementation of tls connections.

**Comment by jvmatl** [comment]
Hi Again! Just wanted to let you know this code is working well in testing and much appreciated!

Yes, in your example above, sure, in my own code I can do what you suggest. But without PSK integration in the built-in library, I can't (or maybe I just don't understand how to?) use tls-ext  in third-party libraries as a substitute for crypto/tls)if their APIs don't accept overrides for their Listeners and Dialers (e.g. in order to have some IoT devices connect to an MQTT broker using tls-psk, I had to fork an existing broker and modify it internally to use the tls-psk package. This works, more or less, but as I'm sure you understand, it is less than ideal because it introduces the pointless maintenance burden of having to keep the forked packages (MQTT brokers, MQTT clients (in order to simulate the devices for testing, etc.)

(That's not a criticism of your work - I'm just frustrated by the Go team's narrow view of what constitutes a legitimate use case for a standard TLS cipher suite -- a cipher suite that exists for precisely to support resource-constrained use cases like the one I am dealing with.)
